/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Arista;
import Clases.Vertice;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author vmbarbosa
 */
public class Interfaz extends javax.swing.JFrame {

    ArrayList<Vertice> vertices = new ArrayList();
    ArrayList<Arista> aristas = new ArrayList();
    String Accion = "Nada";

    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Mapa = new javax.swing.JLabel();
        Menu = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        VerticeIn = new javax.swing.JComboBox<>();
        VerticeDes = new javax.swing.JComboBox<>();
        Distancia = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        VerticeInDFS = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        AddDestino = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        DFS = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(1065, 756, 756, 756));
        setMaximumSize(new java.awt.Dimension(1065, 677));
        setMinimumSize(new java.awt.Dimension(1065, 677));
        setPreferredSize(new java.awt.Dimension(1065, 720));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1070, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mapa.jpg"))); // NOI18N
        Mapa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(Mapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 480));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 480));

        Menu.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VerticeIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        jPanel2.add(VerticeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 190, 30));

        VerticeDes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        jPanel2.add(VerticeDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 191, 30));
        jPanel2.add(Distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 160, 20));

        jButton6.setText("Crear Aristas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 200, 30));

        jLabel6.setText("Distancia:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 60, 40));

        Menu.addTab("tab2", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1266, 0, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 200, 30));

        jLabel3.setText(" Vertice Destino");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 200, 30));

        jComboBox2.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 30));

        jLabel4.setText(" Vertice Inicio");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, 30));

        jLabel5.setText("Distancia:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 70, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Agregar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 250, 30));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 180, 30));

        Menu.addTab("tab1", jPanel1);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        VerticeInDFS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));

        jButton2.setText("Realizar Recorrido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(VerticeInDFS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(628, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(VerticeInDFS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        Menu.addTab("tab3", jPanel6);

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 870, 220));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        jPanel5.setForeground(new java.awt.Color(0, 153, 204));

        AddDestino.setBackground(new java.awt.Color(204, 204, 204));
        AddDestino.setText("Añadir Destino");
        AddDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDestinoActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(204, 204, 204));
        Delete.setText("Eliminar");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        DFS.setBackground(new java.awt.Color(204, 204, 204));
        DFS.setText("Recorrido DFS");
        DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFSActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setText("Recorrido BFS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DFS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AddDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Delete)
                .addGap(18, 18, 18)
                .addComponent(DFS)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 500, 210, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        if (Accion.equals("Añadir")) {

            String nombre = JOptionPane.showInputDialog(this, "Digite el Nombre del nodo que desea crea.", "Vertice", WIDTH);
            if (!nombre.equals("") && !nombre.equals(null)) {
                boolean sw = Colisiones(evt.getX(), evt.getY());
                if (sw == false) {
                    Graphics g = getGraphics();
                    ImageIcon img = new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/40028.png")).getImage());
                    System.out.println(evt.getY() + " " + evt.getX());
                    Vertice vertice = new Vertice(evt.getX(), evt.getY(), nombre);
                    vertices.add(vertice);
                    g.drawImage(img.getImage(), evt.getX(), evt.getY(), 55, 55, null);
                    g.setFont(new Font("TimesRoman", Font.PLAIN, 18));
                    g.setColor(Color.GRAY.darker().darker());
                    g.drawString(nombre, evt.getX() + 3, evt.getY() + 70);
                    g.dispose();
                    LllenarComboBox(VerticeIn);
                    LllenarComboBox(VerticeDes);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No ha escrito ningun nombre.", "Advertencia", HEIGHT);
            }
        } else {
            if (Accion.equals("Eliminar")) {

            }
        }
        Accion = "Nada";
        Mapa.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanel3MouseClicked

    public void LllenarComboBox(JComboBox c) {
        c.removeAllItems();
        c.addItem("...");
        for (Vertice vertice : vertices) {
            c.addItem(vertice.getNombre());
        }
    }


    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Vertice ver = vertices.get(VerticeIn.getSelectedIndex() - 1);
        Vertice ver2 = vertices.get(VerticeDes.getSelectedIndex() - 1);
        Arista arista = new Arista(Integer.parseInt(Distancia.getText()), ver, ver2);
        aristas.add(arista);
        Graphics g = getGraphics();
        g.setColor(Color.yellow.darker());
        Graphics2D g2 = (Graphics2D) g;
        g2.setStroke(new BasicStroke(2));
        g.drawString(Distancia.getText(), (arista.getCentrox()) + 28, arista.getCentroy() + 45);
        g.setColor(Color.blue.darker());
        g.drawLine(ver2.getX() + 28, ver2.getY() + 45, ver.getX() + 28, ver.getY() + 45);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void AddDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDestinoActionPerformed
        Accion = "Añadir";
        Mapa.setCursor(Cursor.getPredefinedCursor(Cursor.CROSSHAIR_CURSOR));
    }//GEN-LAST:event_AddDestinoActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        Accion = "Eliminar";
        Mapa.setCursor(Cursor.getPredefinedCursor(Cursor.CROSSHAIR_CURSOR));
    }//GEN-LAST:event_DeleteActionPerformed

    private void DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFSActionPerformed
        Menu.setSelectedIndex(2);
        LllenarComboBox(VerticeInDFS);
    }//GEN-LAST:event_DFSActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            DFS(vertices.get(VerticeInDFS.getSelectedIndex() - 1));
        } catch (InterruptedException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Graphics g = getGraphics();
        super.paintComponents(g);
        for (Vertice vertice : vertices) {

            ImageIcon img = new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/40028.png")).getImage());
            g.drawImage(img.getImage(), vertice.getX(), vertice.getY(), 55, 55, null);
            g.setFont(new Font("TimesRoman", Font.PLAIN, 18));
            g.setColor(Color.GRAY.darker().darker());
            g.drawString(vertice.getNombre(), vertice.getX() + 3, vertice.getY() + 70);

        }

        for (Arista arista : aristas) {
            g.setColor(Color.yellow.darker());
            Graphics2D g2 = (Graphics2D) g;
            g2.setStroke(new BasicStroke(2));
            g.drawString(String.valueOf(arista.getPeso()), (arista.getCentrox()) + 28, arista.getCentroy() + 45);
            g.setColor(Color.blue.darker());
            g.drawLine(arista.getVerticeFin().getX() + 28, arista.getVerticeFin().getY() + 45, arista.getVerticeIn().getX() + 28, arista.getVerticeIn().getY() + 45);

        }
    }//GEN-LAST:event_formWindowActivated

    void DFS(Vertice vi) throws InterruptedException {
        vi.setEstado(true);

        for (Vertice vk : vi.getVerticesad()) {
            if (vk.isEstado() == false) {
                Thread.sleep(1000);
                dibujarAristas(vk, vi);
                DFS(vk);
            }
        }
    }

    public void ReiniciarEstado() {

    }

    public void dibujarAristas(Vertice vk, Vertice vi) {

        Arista aris = vi.getArista(vk);
        Graphics g = getGraphics();
        super.paintComponents(g);
        for (Vertice vertice : vertices) {

            ImageIcon img = new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/40028.png")).getImage());
            g.drawImage(img.getImage(), vertice.getX(), vertice.getY(), 55, 55, null);
            g.setFont(new Font("TimesRoman", Font.PLAIN, 18));
            g.setColor(Color.GRAY.darker().darker());
            g.drawString(vertice.getNombre(), vertice.getX() + 3, vertice.getY() + 70);

        }

        for (Arista arista : aristas) {
            if (!arista.equals(aris)) {
                g.setColor(Color.yellow.darker());
                Graphics2D g2 = (Graphics2D) g;
                g2.setStroke(new BasicStroke(2));
                g.drawString(String.valueOf(arista.getPeso()), (arista.getCentrox()) + 28, arista.getCentroy() + 45);
                g.setColor(Color.blue.darker());
                g.drawLine(arista.getVerticeFin().getX() + 28, arista.getVerticeFin().getY() + 45, arista.getVerticeIn().getX() + 28, arista.getVerticeIn().getY() + 45);
            }
        }
        g.setColor(Color.red.darker());
        Graphics2D g2 = (Graphics2D) g;
        g2.setStroke(new BasicStroke(2));
        g.drawString(String.valueOf(aris.getPeso()), (aris.getCentrox()) + 28, aris.getCentroy() + 45);
        g.drawLine(aris.getVerticeFin().getX() + 28, aris.getVerticeFin().getY() + 45, aris.getVerticeIn().getX() + 28, aris.getVerticeIn().getY() + 45);
        g.dispose();
    }

    public boolean Colisiones(int x, int y) {
        boolean sw1 = false, sw2 = false, sw3 = false, sw4 = false;
        sw1 = Superposicion(x, y);
        sw2 = Superposicion(x + 55, y);
        sw3 = Superposicion(x, y + 55);
        sw4 = Superposicion(x + 55, y + 55);
        if (sw1 == false && sw2 == false && sw3 == false && sw4 == false) {
            return false;
        } else {
            JOptionPane.showMessageDialog(null, "Ya existe un vertice en esta posicion");
            return true;
        }

    }

    public boolean Superposicion(int x, int y) {
        boolean sw1 = false, sw2 = false, sw3 = false, sw4 = false;
        for (Vertice vertice : vertices) {
            if (x > vertice.getX() || x == vertice.getX()) {
                sw1 = true;
            }
            if (x < vertice.getX() + 55 || x == vertice.getX() + 55) {
                sw2 = true;
            }
            if (y > vertice.getY() || y == vertice.getY()) {
                sw3 = true;
            }
            if (y < vertice.getY() + 55 || y == vertice.getY() + 55) {
                sw4 = true;
            }
            if (sw1 == true && sw2 == true && sw3 == true && sw4 == true) {
                return true;
            } else {
                sw1 = false;
                sw2 = false;
                sw3 = false;
                sw4 = false;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDestino;
    private javax.swing.JButton DFS;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Distancia;
    private javax.swing.JLabel Mapa;
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JComboBox<String> VerticeDes;
    private javax.swing.JComboBox<String> VerticeIn;
    private javax.swing.JComboBox<String> VerticeInDFS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
